apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: traderx
  labels:
    app: account-service
spec:
  type: ClusterIP
  selector:
    app: account-service
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
