apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traderx

resources:
  - namespace.yaml
  - users-service-deployment.yaml
  - users-service-service.yaml
  - users-service-configmap.yaml
  - users-service-secret.yaml
  - users-service-hpa.yaml
  - trades-service-deployment.yaml
  - trades-service-service.yaml
  - trades-service-configmap.yaml
  - trades-service-secret.yaml
  - trades-service-hpa.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-configmap.yaml
  - frontend-secret.yaml
  - frontend-hpa.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
