apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traderx

resources:
  - namespace.yaml
  - account-service-deployment.yaml
  - account-service-service.yaml
  - account-service-configmap.yaml
  - account-service-secret.yaml
  - account-service-hpa.yaml
  - trading-service-deployment.yaml
  - trading-service-service.yaml
  - trading-service-configmap.yaml
  - trading-service-secret.yaml
  - trading-service-hpa.yaml
  - position-service-deployment.yaml
  - position-service-service.yaml
  - position-service-configmap.yaml
  - position-service-secret.yaml
  - position-service-hpa.yaml
  - reference-data-service-deployment.yaml
  - reference-data-service-service.yaml
  - reference-data-service-configmap.yaml
  - reference-data-service-secret.yaml
  - reference-data-service-hpa.yaml
  - people-service-deployment.yaml
  - people-service-service.yaml
  - people-service-configmap.yaml
  - people-service-secret.yaml
  - people-service-hpa.yaml
  - ingress.yaml
