apiVersion: v1
kind: Service
metadata:
  name: reference-data-service
  namespace: traderx
  labels:
    app: reference-data-service
spec:
  type: ClusterIP
  selector:
    app: reference-data-service
  ports:
    - port: 8004
      targetPort: 8004
      protocol: TCP
