apiVersion: v1
kind: Service
metadata:
  name: trading-service
  namespace: traderx
  labels:
    app: trading-service
spec:
  type: ClusterIP
  selector:
    app: trading-service
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
