apiVersion: v1
kind: Service
metadata:
  name: trades-service
  namespace: traderx
  labels:
    app: trades-service
spec:
  type: ClusterIP
  selector:
    app: trades-service
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
