apiVersion: v1
kind: ConfigMap
metadata:
  name: trades-service-config
  namespace: traderx
data:
  APP_PORT: "8002"
  APP_HOST: "0.0.0.0"
  LOG_LEVEL: "INFO"
  USERS_SERVICE_URL: "http://users-service:8001"
