apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: traderx
  labels:
    app: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - name: web-frontend
          image: web-frontend:latest
          ports:
            - containerPort: 18094
          envFrom:
            - configMapRef:
                name: web-frontend-config
          readinessProbe:
            httpGet:
              path: /
              port: 18094
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 18094
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
